[package]
name = "tls"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
viz = { path = "../../viz", features = ["tls", "http2"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

tracing = "0.1"
tracing-subscriber = "0.2"