version = "Two"
unstable_features = true

newline_style = "Unix"
condense_wildcard_suffixes = true
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"

# The following lines may be uncommented on nightly Rust.
# Once these features have stabilized, they should be added to the always-enabled options above.
#unstable_features = true
#imports_granularity = "Crate"
#reorder_impl_items = true
#wrap_comments = true
#comment_width = 100
#normalize_comments = true

#reorder_imports = true
#imports_granularity = "Item"
#group_imports = "StdExternalCrate"
#where_single_line = true
#trailing_comma = "Vertical"
#report_fixme = "Unnumbered"
#overflow_delimited_expr = true
