[package]
name = "viz-core"
version = "0.1.0"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"

[dependencies]
viz-utils = { path = "../viz-utils" }
pin-project = "0.4.9"
anyhow = "1.0.28"
http = "0.2.1"
futures-core = "0.3.4"
futures = "0.3.4"
log = "0.4.8"
async-trait = "0.1.30"
thiserror = "1.0.15"
handle = "0.2.5"
