[package]
name = "viz-core"
version = "0.1.0-alpha"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
description = "Viz Core"
license = "Apache-2.0/MIT"
edition = "2018"

[features]
# cookies = ["cookie"]

[dependencies]
viz-utils = { path = "../viz-utils", version = "0.1.0-alpha" }

handle = "1"

form-data = { git = "https://github.com/viz-rs/form-data.git", version = "0.1.0-dev" }
bytes = "0.6"
http = "0.2"
headers = "0.3"
mime = "0.3"
hyper = { git = "https://github.com/hyperium/hyper.git", version = "0.14.0-dev", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
cookie = { version = "0.14", default-features = false, features = ["percent-encode", "secure"] }
toml = "0.5"
tokio = { version = "0.3", default-features = false, features = ["rt"] }
tokio-tungstenite = "0.12"

[dev-dependencies]
futures-executor = "0.3"
