[package]
name = "viz-core"
version = "0.1.0-alpha"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
description = "Viz Core"
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
viz-utils = { path = "../viz-utils", version = "0.1.0-alpha" }

handle = "1"

form-data = "0.0.6"
bytes = "0.5"
http = "0.2"
mime = "0.3"
hyper = { version = "0.13", features = ["stream"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
futures-executor = "0.3"
