[package]
name = "viz-core"
version = "0.1.0-alpha.1"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
description = "Viz Core"
license = "Apache-2.0/MIT"
edition = "2018"

[features]
# cookies = ["cookie"]

[dependencies]
viz-utils = { path = "../viz-utils", version = "0.1.0-alpha.1" }

handle = "1"

form-data = "0.1.0-dev"
bytes = "1.0"
http = "0.2"
headers = "0.3"
mime = "0.3"
toml = "0.5"
hyper = { version = "0.14", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
cookie = { version = "0.14", default-features = false, features = ["percent-encode", "secure"] }
tokio = { version = "1.0", default-features = false, features = ["rt", "time"] }
tokio-tungstenite = "0.13"
pin-project = "1.0"

[dev-dependencies]
futures-executor = "0.3"
