[package]
name = "viz-core"
version = "0.1.0-alpha"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
description = "Viz Core"
license = "Apache-2.0/MIT"
edition = "2018"

[features]
# cookies = ["cookie"]

[dependencies]
viz-utils = { path = "../viz-utils", version = "0.1.0-alpha" }

handle = "1"

form-data = { git = "https://github.com/viz-rs/form-data.git", version = "0.1.0-dev" }
bytes = "1.0"
http = "0.2"
headers = "0.3"
mime = "0.3"
toml = "0.5"
hyper = { version = "0.14", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
cookie = { version = "0.14", default-features = false, features = ["percent-encode", "secure"] }
tokio = { version = "1.0", default-features = false, features = ["rt", "time"] }
#tokio-tungstenite = "0.12"
tokio-tungstenite = { git = "https://github.com/aknuds1/tokio-tungstenite.git", rev = "21c3d35" }
pin-project = "1.0"

[dev-dependencies]
futures-executor = "0.3"
