[package]
name = "viz-router"
version = "0.1.0-alpha.6"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
description = "Viz Router"
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
viz-core = { path = "../viz-core", version = "0.1.0-alpha.6" }
viz-utils = { path = "../viz-utils", version = "0.1.0-alpha.6" }
path-tree = "0.1"

[dev-dependencies]
futures-executor = "0.3"
serde = { version = "1.0", features = ["derive"] }
hyper = "0.14"
