[package]
name = "viz-router"
version = "0.1.0"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"

[dependencies]
viz-core = { path= "../viz-core", version = "0.1.0" }
viz-utils = { path= "../viz-utils", version = "0.1.0" }
path-tree = "0.1"

[dev-dependencies]
hyper = "0.13"
futures-executor = "0.3"
serde = { version = "1", features = ["derive"] }
