[package]
name = "cookies"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../viz", features = ["middleware", "middleware-cookies"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2"
