[package]
name = "viz-test"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/viz-test"
description = "The core traits and types in for Viz"
keywords = ["async", "framework", "http", "service", "web"]
categories = ["asynchronous", "network-programming", "web-programming"]
publish = false

[dependencies]
viz.workspace = true

sessions = { version = "0.5", features = ["memory"] }
nano-id = "0.3"

http = "=0.2"
reqwest = { version = "0.11", features = ["cookies", "json", "multipart"]}
tokio = { workspace = true, features = ["full"] }
