[package]
name = "static-routes"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../viz" }

hyper.workspace = true 
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
once_cell = "1.16"
