[limits]
json = 8_000_000
form = 1_000_000

[limits.multipart]
field_name_size = 50
stream_size = 10_000_000
buffer_size = 8_192

[cookies]
secret_key = 'WdYqiCCJ6rtH8rp9c4Np8u7cQvNBjvQXjgVRkgPrxgYvDxfKeRJQJyTkKrCEoanA'

[extras]
hello = 'world'
