[package]
name = "async-graphql-example"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
viz = "0.1.2"
async-graphql-viz = { version = "0.1.4" }

async-graphql = "2.10"

slab = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
