[package]
name = "templates"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
viz = { path = "../../viz" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

serde = "1.0"
once_cell = "1.8"

minijinja = "0.5"
sailfish = "0.3"
ramhorns = "0.12"
