[package]
name = "examples"
version = "0.1.0-alpha"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
publish = false

[[example]]
name = "hello"
path = "hello.rs"

[[example]]
name = "hello-smol"
path = "hello-smol.rs"

[dev-dependencies]
viz = { path = "../viz" }
viz-core = { path = "../viz-core" }
viz-router = { path = "../viz-router" }
viz-utils = { path = "../viz-utils" }

serde = { version = "1.0", features = ["derive"] }
ramhorns = "0.9"
bytes = "0.6"
num_cpus = "1"
futures = "0.3"

hyper = { git = "https://github.com/hyperium/hyper.git", version = "0.14.0-dev", features = ["stream", "tcp"] }
tokio = { version = "0.2", features = ["full"] }
smol = "0.4"
