[workspace]
members = ["*"]
exclude = ["tls", "target"]

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
strip = true
debug = false
panic = "abort"
incremental = false
overflow-checks = false
