[package]
name = "examples"
version = "0.1.0-alpha"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
edition = "2018"
publish = false

[[example]]
name = "hello"
path = "hello.rs"

[dev-dependencies]
viz = { path = "../viz", features = ["middleware-full", "sse", "ws"] }

serde = { version = "1.0", features = ["derive"] }
nanoid = "0.3"
ramhorns = "0.10"
bytes = "1.0"
num_cpus = "1"
futures = "0.3"

hyper = { version = "0.14", features = ["http1", "http2", "stream", "tcp", "server"] }
tokio = { version = "1.0", features = ["full"] }
async-stream = "0.3"
pin-project = "1.0"
smol = "1.0"

[dependencies]
redis = "0.19.0"
tokio-stream = "0.1.2"
