[package]
name = "viz-utils"
version = "0.1.0"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
thiserror = "1"

smol = "0.1"
futures-util = "0.3"

serde_json = "1"
serde_urlencoded = "0.6"

log = "0.4"
pretty_env_logger = "0.4"
