[package]
name = "viz"
version = "0.1.0-alpha"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
description = "Fast, flexible, minimalist web framework for Rust"
homepage = "https://viz.rs"
documentation = "https://docs.rs/viz"
repository = "https://github.com/viz-rs/viz"
keywords = ["viz", "http", "web", "framework", "async"]
categories = ["asynchronous", "network-programming", "web-programming::http-server"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
viz-core = { path = "../viz-core", version = "0.1.0-alpha" }
viz-router = { path = "../viz-router", version = "0.1.0-alpha" }
viz-utils = { path = "../viz-utils", version = "0.1.0-alpha" }

sessions = { git = "https://github.com/viz-rs/sessions.git", branch = "smol", features = ["memory-store"] }

hyper = { version = "0.13", features = ["stream", "tcp"] }
uuid = { version = "0.8", features = ["v4"] }
async-io = "0.1"
