name: Security audit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set current week of the year in environnement
        run: echo "CURRENT_WEEK=$(date +%V)" >> $GITHUB_ENV

        #- uses: actions-rs/audit-check@v1
        #with:
        #  token: ${{ secrets.GITHUB_TOKEN }}
      - name: install cargo audit
        run: cargo install --force cargo-audit
      - name: Cargo update
        run: cargo update
      - name: Generate lockfile
        run: cargo generate-lockfile
      - name: Run cargo audit
        run: cargo audit
