name: Security audit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set current week of the year in environnement
        run: echo "CURRENT_WEEK=$(date +%V)" >> $GITHUB_ENV

      - name: Cargo audio
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
